### PR TITLE
Chore/improved examples with docz

### PR DESCRIPTION
**Pull request by dannyrb**
## WIP

image

### Benefits

- Isolated "playgrounds" to render component
- Quick launch an example in a codesandbox
- Toggle to see code used to generate example
- Runs against pre-built component code; so you can use docs as live-reload while you develop components
- Leverges `.mdx` so we can use Markdown and `jsx` in the same file
- Support for TypeScript, Emotion, StyledComponents, etc. (if/when we decide to use them)

### TODO

- [x] Replace all existing examples in `examples/`
- [x] Remove `examples/`
- [x] Usage docs
- [x] Next steps / Guidelines as we refine this component library
    - See below "next steps"
- [x] Pre - v1.0 warning in docs
- [x] Clean up README to follow `cornerstone.js` template
- [x] Tag reviewers
- [x] Notify stakeholders to use strict versioning until we're at `v1.0`
   - [ ] Merge and bump version

### Next Steps

Moved to roadmap project: https://github.com/OHIF/react-viewerbase/projects/1

- Contributing.md
    - Mention `react-powerplug`
- Wizard steps for bug, feature, question (see docz repo)
- Create issue for side-by-side jest tests
- Semantic-release to make versioning / releases less painful
- [x] Update `OHIF/Viewer/react` to use latest; create issues caused by change
    - https://github.com/OHIF/Viewers/pull/384

### CODE REVIEW

**Comment by pieper** [comment]
Looks cool @dannyrb 👍 - is there a live example (e.g. netlify?)

**Comment by dannyrb** [comment]
@pieper I should have something up before the end of the day you can play with. I'll move this PR out of `DRAFT` when it's ready 👍

**Comment by dannyrb** [comment]
This appears to be killing our `react` and `react-dom` peerDependencies:

https://www.netlify.com/docs/build-gotchas/#yarn

**Comment by dannyrb** [comment]
Looking into what our issue is here. The local `dist` functions as expected when served over a local webserver. However, the Netlify output appears to build differently:

image

We're using a `yarn.lock` to restore dependencies. This appears to be a transpilation issue caused by some difference in my local and the remote environment.

**Comment by dannyrb** [comment]
- Installed [nvm for windows](https://github.com/coreybutler/nvm-windows)
- Ran `nvm list available`
- Updated `.nvmrc` to `UTF-8` and an available node version

Hasn't resolved the issue.

**Comment by dannyrb** [comment]
I tried blowing everything out and a clean clone -- Still works locally.
I'll try using my Linux Subsystem for windows after bit to see if the OS produces different results? At a bit of a loss here. Created a related issue in the `docz` repository.

**Comment by dannyrb** [comment]
Annnd we have liftoff 🚀 
Only ~15 tries to resolve that issue 😅 
Back to cleaning up the existing component styles and getting started docs 👷 ⛏

**Comment by dannyrb** [comment]
@pieper, it's not ready for review, but the preview is up:
https://deploy-preview-50--ohif-react-viewerbase.netlify.com/

If you have any questions/comments, please don't hesitate to 💬

**Comment by pieper** [comment]
Great progress @dannyrb ! 👍

**Comment by dannyrb** [comment]
While not without issues, I think this sets us up with a nice framework to continually improve, document, and test our component library. I'm hoping to gather some thoughts/feedback, create some guiding "next-step" issues, and then merge this PR.

I've tried to at least cover the existing examples/use cases here: https://react.ohif.org/

`docz` v1 has _just_ dropped, so I'm hoping this will be resolved soon:
https://github.com/pedronauck/docz/issues/777

Tagging: @biharck and @galelis

**Comment by biharck** [comment]
Awesome job @dannyrb! 👍

**Pull request merged**
